### ISSUE TITLE
Migrating from Wordpress to Directus

### ISSUE THREAD

**Issue by mvhammedali** [directus-labs/guest-authoring#118]
### What is your idea?

This is to provide a comprehensive guide for users who are considering transitioning their content management system from Wordpress to Directus. This guide aims to assist users in understanding the process involved in migrating content, data, and functionalities from Wordpress to Directus, while also highlighting the benefits and considerations of making such a transition.

### What are the key takeaways from your post?

- Understanding the Differences
- Reasons for Migrating to Directus?
- Steps To Migrate Content From WordPress 
- Data Migration Strategies

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We'd love to have this piece written. I'd like it to be a good, in-depth, step-by-step piece for at least data migration (collections, fields, relations, and data including files). 

There's also probably a process worth mentioning around understand the difference between WP and Directus (headless-only, vs most-commonly an integrated CMS) and auditing plugins because there isn't a 1:1 for many - understanding the WHY of plugins is more important than replacing them. 

Based on the agreed scope we can pay $500 for this post. Normally I'd set a deadline but this piece of content is interesting for us to get out ASAP. When do you think you could have a first draft done?

**Comment by mvhammedali** [comment]
It will be available by April 7

**Comment by phazonoverload** [comment]
Great, let's make that the deadline for the first draft then.

The process is detailed in the README of this repo 😄
