### ISSUE TITLE
How to Build CRUD Application Using Directus and Flutter

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#86]
### What is your idea?

This article will show developers how to integrate Directus with Flutter by creating a CRUD Task Manager mobile application.

### What are the key takeaways from your post?

This article will help developers know how to use Directus and Flutter to build a Task Manager application. In this article, I will be building a mobile application that integrates with Directus to fetch and save records.

Outlines of the application include:

- Setting Up the Development Environment
- Setting up a new Flutter project.
- Setup the Backend with Directus Server
- Building the User Interface with Flutter
- Integrating Flutter with Directus
- Handling State and Network Responses

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
If this could follow the standard getting started format we have instead of being a task manager: 

- Initialize Project (to the point of running dev server)
- Set up requests/env vars/anything needed to call Directus
- Using Global Metadata and Settings
- Creating Pages With Directus
- Creating Blog Posts With Directus
- Create Blog Post Listing
- Create Blog Post Single
- Add Navigation

Here are the current examples: https://docs.directus.io/guides/frameworks

We could do a further application which handles create/update/delete operations, and auth, if this post does well 😄 

Based on the agreed scope we can pay $250 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by Claradev32** [comment]
Great!, the content schedule and recommendations works for me. I look forward to getting started :)

**Comment by phazonoverload** [comment]
Hi @Claradev32 are you still interested in writing this? I've not seen a draft yet :)

**Comment by Claradev32** [comment]
Hi @phazonoverload 
I have been working on it already. I will send a PR this week.
